/**
 * Laravel 6.0
 */
export const FieldTypeMap = new Map([
    ['bigIncrements', 'integer'],
    ['bigInteger', 'integer'],
    ['binary', 'string'],
    ['boolean', 'boolean'],
    ['char', 'string'],
    ['date', 'string'],
    ['dateTime', 'string'],
    ['dateTimeTz', 'string'],
    ['decimal', 'string'],
    ['double', 'double'],
    ['enum', 'string'],
    ['float', 'float'],
    ['geometry', 'string'],
    ['geometryCollection', 'string'],
    ['increments', 'integer'],
    ['integer', 'integer'],
    ['ipAddress', 'string'],
    ['json', 'string'],
    ['jsonb', 'string'],
    ['lineString', 'string'],
    ['longText', 'string'],
    ['macAddress', 'string'],
    ['mediumIncrements', 'integer'],
    ['mediumInteger', 'integer'],
    ['mediumText', 'string'],
    ['morphs', 'string'],
    ['uuidMorphs', 'string'],
    ['multiLineString', 'string'],
    ['multiPoint', 'string'],
    ['multiPolygon', 'string'],
    ['point', 'string'],
    ['polygon', 'string'],
    ['set', 'string'],
    ['smallIncrements', 'integer'],
    ['smallInteger', 'integer'],
    ['string', 'string'],
    ['text', 'string'],
    ['time', 'string'],
    ['timeTz', 'string'],
    ['timestamp', 'string'],
    ['timestampTz', 'string'],
    ['tinyIncrements', 'integer'],
    ['tinyInteger', 'integer'],
    ['uuid', 'string'],
])

export const CommonTypeList = ['integer', 'char', 'string', 'text', 'dateTime', 'timestamp', 'decimal', 'float']
